version: '3'

networks:
  backend:
    driver: bridge

services:
  server:
    container_name: stil_server
    build:
      context: ./
      dockerfile: Dockerfile.server
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    env_file:
      - ./.env
    networks:
      - backend
    ports:
      - 8080:3000
    expose: [8080]
    restart: always

  mongo:
    container_name: stil_mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    expose: [27017]
    networks:
      - backend

    